#!/usr/bin/awk -f
# Parse compiler errors/warnings: file:line:col: error/warning: message

/^([A-Za-z]:)?[^:]+:[0-9]+:[0-9]*:? error:/ {
    print make_absolute($0)
}

WARN && /^([A-Za-z]:)?[^:]+:[0-9]+:[0-9]*:? warning:/ {
    print make_absolute($0)
}
