#!/usr/bin/awk -f
# Parse compiler errors/warnings: file:line:col: error/warning: message

function prefix(line) {
    if (line ~ /^\//) return line
    return DIR "/" line
}

/^[^:]+:[0-9]+:[0-9]*:? error:/ {
    print prefix($0)
}

WARN && /^[^:]+:[0-9]+:[0-9]*:? warning:/ {
    print prefix($0)
}
