#!/usr/bin/awk -f
# Parse MSVC errors/warnings: file(line,col): error/warning CNNNN: message [project.vcxproj]

function parse_msvc() {
    str = $0
    sub(/ \[.*\]$/, "", str)

    match(str, /\(([0-9]+),([0-9]+)\)/, loc)
    file = substr(str, 1, RSTART - 1)

    msg = substr(str, RSTART + RLENGTH)
    sub(/^: /, "", msg)

    emit(file, loc[1], loc[2], msg)
}

/^[A-Za-z]:[^(]+\([0-9]+(,[0-9]+)?\): error/ {
    parse_msvc()
}

WARN && /^[A-Za-z]:[^(]+\([0-9]+(,[0-9]+)?\): warning/ {
    parse_msvc()
}
