#!/bin/bash
set -e
cd "$(dirname "$0")"

SOURCE_DIR="$(pwd)"
BUILD_DIR="_build"
BUILD_TYPE="Debug"

cmake -S "$SOURCE_DIR" -B "$BUILD_DIR" \
    -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

cmake --build "$BUILD_DIR" \
    --parallel

ctest --test-dir "$BUILD_DIR" \
    --output-on-failure
