#!/bin/bash

set -e

git worktree list --porcelain | awk '
    /^worktree / { path = substr($0, 10) }
    /^branch /   { branch = substr($0, 8)
                    sub("refs/heads/", "", branch) }
    /^HEAD /     { head = substr($0, 6) }
    /^detached/  { branch = substr(head, 1, 7) }
    /^bare/      { branch = "(bare)" }
    /^$/ {
        if (path != "") print path "\t" branch
        path = ""; branch = ""; head = ""
    }
    END {
        if (path != "") print path "\t" branch
    }
' | while IFS=$'\t' read -r path branch; do
    dirty=""
    if [[ "$branch" != "(bare)" ]]; then
        if [[ -n $(git -C "$path" status --porcelain 2>/dev/null) ]]; then
            dirty=" [dirty]"
        fi
    fi
    printf "%-40s %-20s%s\n" "$path" "$branch" "$dirty"
done
