#!/bin/bash

count=1
if [[ $# -ge 1 ]]; then
    count="$1"
fi

if ! [[ "$count" =~ ^[0-9]+$ ]]; then
    echo "Error: Argument must be a number."
    echo "Usage: git last [count]"
    exit 1
fi

if [[ $count -eq 1 ]]; then
    git log -1 --stat HEAD
else
    git log -"$count" --oneline --decorate --graph
fi